stages:
    - test
    - build
    - artifact

test:
    stage: test
    image: golang
    cache:
        paths:
            - /apt-cache
            - /go/src/github.com
            - /go/src/golang.org
            - /go/src/google.golang.org
            - /go/src/gopkg.in
            - /go/src/gitlab.zitcom.dk
    script:
        - 'sh scripts/pipeline/test.sh'

build:
    stage: build
    image: golang
    cache:
        paths:
            - /apt-cache
            - /go/src/github.com
            - /go/src/golang.org
            - /go/src/google.golang.org
            - /go/src/gopkg.in
            - /go/src/gitlab.zitcom.dk
    script:
        - 'sh scripts/pipeline/build.sh'
    artifacts:
        paths:
            - php-dependency-checker
        expire_in: 1 day

artifact:branch:
    stage: artifact
    image:
        name: cgswong/aws:aws
        entrypoint: [""]
    script:
        - "aws s3 cp --acl public-read php-dependency-checker s3://smartweb-artifacts/php-dependency-checker/php-dependency-checker-${CI_COMMIT_SHA}"
    dependencies:
        - build
    when: manual

artifact:latest:
    stage: artifact
    image:
        name: cgswong/aws:aws
        entrypoint: [""]
    script:
        - 'aws s3 cp --acl public-read php-dependency-checker s3://smartweb-artifacts/php-dependency-checker/php-dependency-checker-latest'
        - "aws s3 cp --acl public-read php-dependency-checker s3://smartweb-artifacts/php-dependency-checker/php-dependency-checker-${CI_COMMIT_SHA}"
    dependencies:
        - build
    only:
        - master
